# =========================
# 1. Load Libraries & Setup
# =========================

# List of required libraries
libs <- c(
  "tidyverse", "grid", "libcoin", "mvtnorm", "partykit",
  "LTRCtrees", "labelled", "future.apply", "tictoc", "parallel", "doParallel",
  "foreach", "survival", "flexsurv", "DEoptim", "GenSA", "magrittr", "methods"
)
# Install any missing packages
installed_packages <- libs %in% rownames(installed.packages())
if (any(!installed_packages)) install.packages(libs[!installed_packages])
# Load all libraries
invisible(lapply(libs, require, character.only = TRUE))

# =========================
# 2. S4 Classes & Generics
# =========================

setClassUnion("data.frameOrNULL", c("data.frame", "NULL"))

#' @title PAC and PACFit S4 Classes and Methods
#'
#' @description
#' This code defines two S4 classes, \code{PAC} and \code{PACFit}, for modelling and fitting parametric age-cohort (PAC) survival models in R.
#' It also provides associated methods for model initialization, display, and core model functions.
#'
#' @section Classes:
#' \describe{
#'   \item{\code{PAC}}{
#'     Represents a parametric age-cohort model.
#'     \itemize{
#'       \item{\code{name}: Character string, model name.}
#'       \item{\code{params}: Numeric vector, model parameters.}
#'       \item{\code{survival_}: Function, computes survival probability.}
#'       \item{\code{mu_}: Function, computes hazard function.}
#'       \item{\code{cumhaz_}: Function, computes cumulative hazard.}
#'       \item{\code{bounds}: List, parameter bounds.}
#'     }
#'   }
#'   \item{\code{PACFit}}{
#'     Represents a fitted PAC model.
#'     \itemize{
#'       \item{\code{model}: A \code{PAC} object.}
#'       \item{\code{data}: List containing training and test data.}
#'       \item{\code{data_train}: Data frame, training data.}
#'       \item{\code{data_test}: Data frame, test data.}
#'       \item{\code{fit_results}: List, results from model fitting.}
#'       \item{\code{fitted}: Logical, indicates if model is fitted.}
#'     }
#'   }
#' }
#'
#' @section Methods:
#' \describe{
#'   \item{\code{show}}{Displays a summary of a \code{PAC} or \code{PACFit} object.}
#'   \item{\code{initialize}}{Custom initializer for \code{PACFit} objects, handling data assignment.}
#'   \item{\code{mu}}{Generic and method for computing the hazard function for a \code{PAC} model.}
#'   \item{\code{survival}}{Generic and method for computing the survival function for a \code{PAC} model.}
#'   \item{\code{cumhaz}}{Generic and method for computing the cumulative hazard for a \code{PAC} model.}
#'   \item{\code{logllh}, \code{get_logllh}}{Generics for log-likelihood computation.}
#'   \item{\code{fit}}{Generic for fitting a \code{PACFit} model.}
#'   \item{\code{AIC}, \code{BS}}{Generics for model evaluation metrics.}
#' }
#'
#' @seealso \code{\link[methods]{setClass}}, \code{\link[methods]{setMethod}}, \code{\link[methods]{setGeneric}}
#'
#' @author
#' Generated by GitHub Copilot
setClass(
  "PAC",
  slots = list(
    name = "character",
    params = "numeric",
    survival_ = "function",
    mu_ = "function",
    cumhaz_ = "function",
    bounds = "list"
  )
)

setClass(
  "PACFit",
  slots = list(
    model = "PAC",
    data = "list",
    data_train = "data.frameOrNULL",
    data_test  = "data.frameOrNULL",
    fit_results = "list",
    fitted = "logical"
  )
)

setMethod("show", "PAC", function(object) {
  cat("PAC Model: ", object@name, "\n")
})

setMethod("show", "PACFit", function(object) {
  cat("PACFit Model: ", object@model@name, "\n")
  if (object@fitted) {
    cat("Fit Results:",object@fit_results$value,"\n")
    cat("Parameters:", object@model@params, "\n")
  }
})

#' @describeIn PACFit
#' Custom initializer for PACFit objects.
#'
#' Assigns the model and data slots, handling both combined data lists and separate train/test data frames.
#' Initializes fit_results as an empty list and sets fitted to FALSE.
#'
#' @param .Object The PACFit object being initialized.
#' @param model A PAC model object.
#' @param data Optional list containing 'train' and 'test' data frames.
#' @param data_train Optional training data frame.
#' @param data_test Optional test data frame.
#' @return The initialized PACFit object.
setMethod("initialize", "PACFit", function(.Object, model, data=NULL, data_train=NULL, data_test=NULL) {
  .Object@model <- model
  if (!is.null(data)) {
    .Object@data <- data
    .Object@data_train <- if (is.null(data$train)) NULL else data$train
    .Object@data_test  <- if (is.null(data$test))  NULL else data$test
  } else {
    .Object@data <- if (!is.null(data_train) || !is.null(data_test)) list(train=data_train, test=data_test) else NULL
    .Object@data_train <- data_train
    .Object@data_test  <- data_test
  }
  .Object@fit_results <- list()
  .Object@fitted <- FALSE
  .Object
})

setGeneric("mu", function(model, ...) standardGeneric("mu"))
setMethod("mu", "PAC", function(model, x) model@mu_(model@params, x))

setGeneric("survival", function(model, ...) standardGeneric("survival"))
setMethod("survival", "PAC", function(model, x) model@survival_(model@params, x))

setGeneric("cumhaz", function(model, ...) standardGeneric("cumhaz"))
setMethod("cumhaz", "PAC", function(model, x, t) model@cumhaz_(model@params, x, t))

setGeneric("logllh", function(model, ...) standardGeneric("logllh"))
setGeneric("get_logllh", function(model, ...) standardGeneric("get_logllh"))

setGeneric("fit", function(model_fit, ...) standardGeneric("fit"))
setGeneric("AIC", function(model_fit, ...) standardGeneric("AIC"))
setGeneric("BS", function(model_fit, ...) standardGeneric("BS"))

# =========================
# 3. Model Functions
# =========================

# --- Gompertz ---
# Survival function for the Gompertz model
survival_gompertz <- function(par, x) {
  a <- par[1]; b <- par[2]
  exp(-exp(a) * (exp(b * x) - 1) / b)
}
# Cumulative hazard function for the Gompertz model
cumulative_hazard_gompertz <- function(par, x, t) {
  a <- par[1]; b <- par[2]
  (exp(b * t) - 1) / b * exp(a + b * x)
}
# Force of mortality (hazard) for the Gompertz model
forceofmortality_gompertz <- function(par, x) {
  a <- par[1]; b <- par[2]
  exp(a + b * x)
}

# --- Gompertz-Makeham ---
# Survival function for the Gompertz-Makeham model
survival_makeham <- function(par, x) {
  a <- par[1]; b <- par[2]; lambda <- par[3]
  exp(-exp(a) * (exp(b * x) - 1) / b - x * lambda)
}
# Cumulative hazard function for the Gompertz-Makeham model
cumulative_hazard_makeham <- function(par, x, t) {
  a <- par[1]; b <- par[2]; lambda <- par[3]
  (exp(b * t) - 1) / b * exp(a + b * x) + lambda * t
}
# Force of mortality (hazard) for the Gompertz-Makeham model
forceofmortality_makeham <- function(par, x) {
  a <- par[1]; b <- par[2]; lambda <- par[3]
  exp(a + b * x) + lambda
}

# --- Perks ---
# Survival function for the Perks model
survival_perks <- function(par, x) {
  a <- par[1]; b <- par[2]; gam <- par[3]; lambda <- par[4]
  ((1 + exp(a + gam)) / (1 + exp(a + gam + b * x)))^(exp(-gam) / b) / exp(lambda * x)
}
# Cumulative hazard function for the Perks model
cumulative_hazard_perks <- function(par, x, t) {
  a <- par[1]; b <- par[2]; gam <- par[3]; lambda <- par[4]
  # Different forms depending on b for numerical stability
  if (b > 2) {
    tolog = exp(b * t) + exp(-(a + gam + b * (x - t)))
  } else if (b > 1) {
    tolog = exp(b * t) + (exp(-b * t) - 1) / (exp(-b * t) + exp(a + gam + b * (x - t)))
  } else {
    tolog = (1 + exp(a + gam + b * (x + t))) / (1 + exp(a + gam + b * x))
  }
  exp(-gam) / b * log(tolog) + lambda * t
}
# Force of mortality (hazard) for the Perks model
forceofmortality_perks <- function(par, x) {
  a <- par[1]; b <- par[2]; gam <- par[3]; lambda <- par[4]
  if (b > 1) {
    1 / (exp(-(a + b * x)) + exp(gam)) + lambda
  } else {
    exp(a + b * x) / (1 + exp(a + gam + b * x)) + lambda
  }
}

# --- Beard ---
# Survival function for the Beard model
survival_beard <- function(par, x) {
  a <- par[1]; b <- par[2]; gam <- par[3]
  ((1 + exp(a + gam)) / (1 + exp(a + gam + b * x)))^(exp(-gam) / b)
}
# Cumulative hazard function for the Beard model
cumulative_hazard_beard <- function(par, x, t) {
  a <- par[1]; b <- par[2]; gam <- par[3]
  # Different forms depending on b for numerical stability
  if (b > 2) {
    tolog = exp(b * t) + exp(-(a + gam + b * (x - t)))
  } else if (b > 1) {
    tolog = exp(b * t) + (exp(-b * t) - 1) / (exp(-b * t) + exp(a + gam + b * (x - t)))
  } else {
    tolog = (1 + exp(a + gam + b * (x + t))) / (1 + exp(a + gam + b * x))
  }
  exp(-gam) / b * log(tolog)
}
# Force of mortality (hazard) for the Beard model
forceofmortality_beard <- function(par, x) {
  a <- par[1]; b <- par[2]; gam <- par[3]
  if (b > 1) {
    1 / (exp(-(a + b * x)) + exp(gam))
  } else {
    exp(a + b * x) / (1 + exp(a + gam + b * x))
  }
}

# --- Kannisto ---
# Survival function for the Kannisto model
survival_kannisto <- function(par, x) {
  a <- par[1]; b <- par[2]
  ((1 + exp(a)) / (1 + exp(a + b * x)))^(1 / b)
}
# Cumulative hazard function for the Kannisto model
cumulative_hazard_kannisto <- function(par, x, t) {
  a <- par[1]; b <- par[2]
  # Different forms depending on b for numerical stability
  if (b > 2) {
    tolog = exp(b * t) + exp(-(a + b * (x - t)))
  } else if (b > 1) {
    tolog = exp(b * t) + (exp(-b * t) - 1) / (exp(-b * t) + exp(a + b * (x - t)))
  } else {
    tolog = (1 + exp(a + b * (x + t))) / (1 + exp(a + b * x))
  }
  1 / b * log(tolog)
}
# Force of mortality (hazard) for the Kannisto model
forceofmortality_kannisto <- function(par, x) {
  a <- par[1]; b <- par[2]
  if (b > 1) {
    1 / (exp(-(a + b * x)) + 1)
  } else {
    exp(a + b * x) / (1 + exp(a + b * x))
  }
}

# --- Thatcher ---
# Survival function for the Thatcher model
survival_thatcher <- function(par, x) {
  a <- par[1]; b <- par[2]; lambda <- par[3]
  ((1 + exp(a)) / (1 + exp(a + b * x)))^(1 / b) / exp(lambda * x)
}
# Cumulative hazard function for the Thatcher model
cumulative_hazard_thatcher <- function(par, x, t) {
  a <- par[1]; b <- par[2]; lambda <- par[3]
  # Different forms depending on b for numerical stability
  if (b > 2) {
    tolog = exp(b * t) + exp(-(a + b * (x - t)))
  } else if (b > 1) {
    tolog = exp(b * t) + (exp(-b * t) - 1) / (exp(-b * t) + exp(a + b * (x - t)))
  } else {
    tolog = (1 + exp(a + b * (x + t))) / (1 + exp(a + b * x))
  }
  1 / b * log(tolog) + lambda * t
}
# Force of mortality (hazard) for the Thatcher model
forceofmortality_thatcher <- function(par, x) {
  a <- par[1]; b <- par[2]; lambda <- par[3]
  if (b > 1) {
    1 / (exp(-(a + b * x)) + 1) + lambda
  } else {
    exp(a + b * x) / (1 + exp(a + b * x)) + lambda
  }
}

# =========================
# 4. Model Fitting & Evaluation
# =========================

# Log-likelihood method for PAC models
setMethod("logllh", "PAC", function(model, par, x, r, i) {
  # Return -Inf if parameters are not finite or if the second parameter is too close to zero
  if (any(!is.finite(par)) || abs(par[2]) <= 1e-6) return(-Inf)
  # Compute cumulative hazard at observed time
  H <- model@cumhaz_(par, x, r - x)
  # Compute hazard at event time and at baseline
  mu_r <- model@mu_(par, r)
  mu_0 <- model@mu_(par, 0)
  # Check for invalid values
  if (any(!is.finite(H)) || any(H <= 0)) return(-Inf)
  if (any(!is.finite(mu_r)) || any(mu_r <= 0)) return(-Inf)
  if (any(!is.finite(mu_0)) || any(mu_0 <= 0)) return(-Inf)
  # Log-likelihood: i*log(mu_r) - H
  ll <- i * log(mu_r) - H
  return(ll)
})

# Method to get log-likelihood for a dataset (vectorized)
setMethod("get_logllh", "PAC", function(model, data_train, par = NULL) {
  if (is.null(par)) par <- model@params
  logllh(
    model,
    par = par,
    x = data_train$birthage,
    r = data_train$censoredage,
    i = data_train$DthIndicator
  )
})

# Fit method for PACFit: fits the model to training data using GenSA optimizer
setMethod("fit", "PACFit", function(model_fit, data_train, patience = 30, tol = 1e-6, verbose = FALSE) {
  PAC <- model_fit@model
  # Negative log-likelihood function to minimize
  raw_fn <- function(par) {
    -sum(logllh(
      PAC,
      par = par,
      x = data_train$birthage,
      r = data_train$censoredage,
      i = data_train$DthIndicator
    ))
  }
  lower <- PAC@bounds$lower
  upper <- PAC@bounds$upper
  initial <- PAC@params
  # Early stopping mechanism based on patience and tolerance
  patience_tracker <- local({
    best_val <- Inf; best_par <- initial; counter <- 0; done <- FALSE
    function(par) {
      if (done) return(1e10)
      val <- raw_fn(par)
      if ((best_val - val) > tol) {
        best_val <<- val; best_par <<- par; counter <<- 0
      } else {
        counter <<- counter + 1
      }
      if (counter >= patience) done <<- TRUE
      return(val)
    }
  })
  # Run the GenSA optimizer
  result <- GenSA(
    par = initial,
    fn = patience_tracker,
    lower = lower,
    upper = upper,
    control = list(max.call = 2000, verbose = verbose)
  )
  # Update model parameters and fit status
  model_fit@model@params <- result$par
  model_fit@fitted <- TRUE
  model_fit@fit_results <- result
  return(model_fit)
})

# AIC method for PACFit: computes Akaike Information Criterion for fitted model
setMethod("AIC", "PACFit", function(model_fit) {
  if (!model_fit@fitted) stop("Model has not been fitted yet.")
  k <- length(model_fit@model@params)
  loglik <- -model_fit@fit_results$value
  aic <- -2 * loglik + 2 * k
  return(aic)
})

# =========================
# 5. Utility & Evaluation Functions
# =========================

# ---- Integrated Brier Score (IBS) ----
# Computes empirical survival curves for a dataset and caches them in Surv_info_total.
# Used for Brier Score calculation.
empirical_survival <- function(data, data_name, x_min = 80, x_max = 115) {
  if (!exists("Surv_info_total")) stop("Surv_info_total is not defined in the global environment.")
  if (exists(data_name, where=Surv_info_total)) return(Surv_info_total[[data_name]])
  # Survival for birth age (all events)
  Surv_BA = Surv(time = data$birthage, event = rep(1, nrow(data)))
  survfit_BA = survfit(Surv_BA ~ 1)
  sf_BA = summary(survfit_BA, times = x_min:x_max)$surv
  # Survival for censored age (non-deaths)
  Surv_CA = Surv(time = data$censoredage, event = 1 - data$DthIndicator)
  survfit_CA = survfit(Surv_CA ~ 1)
  sf_CA = summary(survfit_CA, times = x_min:x_max)$surv
  # Store in global cache
  Surv_info_total[[data_name]] <<- list(
    survfit_BA = survfit_BA,
    survfit_CA = survfit_CA,
    sf_BA = sf_BA,
    sf_CA = sf_CA
  )
  save(Surv_info_total, file = paste0("Surv_info_total.RData"))
  return(Surv_info_total[[data_name]])
}

# ---- Brier Score (BS) for a single time/individual ----
# Calculates the Brier Score for a given age, individual, and model.
BS_raw <- function(x, birthage, censoredage, DthIndicator, Sfunc, par, Surv_info, x_min = 80) {
  S <- Sfunc(par, x)
  S0 <- Sfunc(par, birthage)
  S <- S / S0
  if (x < birthage) {
    bs <- 0
  } else if (censoredage <= x && DthIndicator == 1) {
    # Event occurred before or at time x
    rawbs <- S^2
    CA_survfit <- Surv_info$survfit_CA
    if (max(Surv_info$survfit_CA$time) <= censoredage){
      SCA = 1 / CA_survfit$n
    }
    else{
      SCA <- summary(CA_survfit, times = censoredage)$surv
    }
    bs <- rawbs / SCA
  } else if (censoredage > x) {
    # Censored after time x
    rawbs <- (1 - S)^2
    idx <- x - x_min + 1
    sfBA <- Surv_info$sf_BA[idx]
    sfCA <- Surv_info$sf_CA[idx]
    bs <- rawbs / (1 - sfBA) / sfCA
    # Fallback for numerical issues
    if (!is.finite(bs) || is.nan(bs) || is.na(bs)) {
      if (max(Surv_info$survfit_BA$time) <= x) {
        sfBA = 0
      }
      if (max(Surv_info$survfit_CA$time) <= x) {
        sfCA = 1 / Surv_info$survfit_CA$n
      }
      bs <- rawbs / (1 - sfBA) / sfCA
    }
  } else {
    bs <- 0
  }
  return(bs)
}

# ---- Integrated Brier Score (IBS) for a dataset ----
# Applies BS_raw across ages 80:115 and all individuals, then averages.
setMethod("BS", "PACFit", function(model_fit, data_valid, Surv_info, x_min = 80, x_max = 115) {
  if (!model_fit@fitted) stop("Model has not been fitted yet.")
  bs_values <- c()
  for (age in c(x_min:x_max)) {
    tempbs <-
      mapply(
        function(birthage, censoredage, DthIndicator) {
          BS_raw(
            x = age,
            birthage = birthage,
            censoredage = censoredage,
            DthIndicator = DthIndicator,
            Sfunc = model_fit@model@survival_,
            par = model_fit@model@params,
            Surv_info = Surv_info
          )
        },
        birthage = data_valid$birthage,
        censoredage = data_valid$censoredage,
        DthIndicator = data_valid$DthIndicator
      )
    bs_values <- bs_values %>% c(mean(tempbs))
  }
  return(mean(bs_values))
}
)

# =========================
# 6. Model Initializers
# =========================

#' @title PAC Model Initializer Functions
#'
#' @description
#' Provides constructor functions for each parametric age-cohort (PAC) survival model.
#' Each function returns a PAC S4 object with appropriate model functions and parameter bounds.
#'
#' @details
#' - InitPAC: Generic initializer for PAC S4 objects.
#' - GompertzPAC: Gompertz model.
#' - MakehamPAC: Gompertz-Makeham model.
#' - PerksPAC: Perks model.
#' - BeardPAC: Beard model.
#' - KannistoPAC: Kannisto model.
#' - ThatcherPAC: Thatcher model.
#'
#' @seealso \code{\link{setClass}}, \code{\link{setMethod}}
#'
#' @author
#' Generated by GitHub Copilot

# Generic initializer for PAC S4 objects
#' @title Generic PAC Model Initializer
#' @description Constructs a PAC S4 object with specified model functions and parameter bounds.
#' @param name Character string, the model name.
#' @param params Numeric vector, initial parameter values.
#' @param survival_ Function, computes survival probability.
#' @param mu_ Function, computes hazard function.
#' @param cumhaz_ Function, computes cumulative hazard.
#' @param bounds List, containing 'lower' and 'upper' parameter bounds.
#' @return An object of class \code{PAC}.
InitPAC <- function(name, params, survival_, mu_, cumhaz_, bounds) {
  new("PAC",
      name = name,
      params = params,
      survival_ = survival_,
      mu_ = mu_,
      cumhaz_ = cumhaz_,
      bounds = bounds
  )
}
#' @param bounds List, containing 'lower' and 'upper' parameter bounds.
#'
#' @return An object of class \code{PAC}.

# ---- Gompertz Model ----
DEFAULT_PARAMS_GOMPERTZ <- c(-10, 0.1) # a, b
DEFAULT_BOUNDS_GOMPERTZ <- list(lower = c(-20, 0.0001), upper = c(20, 1)) # a, b
#' @title Gompertz Model Initializer
#' @description Constructs a PAC S4 object for the Gompertz survival model.
#' @param params Numeric vector of initial parameter values (default: c(-10, 0.1)).
#' @param bounds List with 'lower' and 'upper' numeric vectors for parameter bounds.
#' @return An object of class \code{PAC} for the Gompertz model.
GompertzPAC <- function(params = DEFAULT_PARAMS_GOMPERTZ,
                        bounds = DEFAULT_BOUNDS_GOMPERTZ) {
  InitPAC("Gompertz", params, survival_gompertz, forceofmortality_gompertz, cumulative_hazard_gompertz, bounds)
}

# ---- Gompertz-Makeham Model ----
DEFAULT_PARAMS_MAKEHAM <- c(-10, 0.1, 0) # a, b, lambda
DEFAULT_BOUNDS_MAKEHAM <- list(lower = c(-20, 0.0001, 0), upper = c(20, 1, 1)) # a, b, lambda
#' @title Gompertz-Makeham Model Initializer
#' @description Constructs a PAC S4 object for the Gompertz-Makeham survival model.
#' @param params Numeric vector of initial parameter values (default: c(-10, 0.1, 0)).
#' @param bounds List with 'lower' and 'upper' numeric vectors for parameter bounds.
#' @return An object of class \code{PAC} for the Gompertz-Makeham model.
MakehamPAC <- function(params = DEFAULT_PARAMS_MAKEHAM,
                       bounds = DEFAULT_BOUNDS_MAKEHAM) {
  InitPAC("Gompertz-Makeham", params, survival_makeham, forceofmortality_makeham, cumulative_hazard_makeham, bounds)
}

# ---- Perks Model ----
DEFAULT_PARAMS_PERKS <- c(-15, 0.1, 0.7, 0) # a, b, gam, lambda
DEFAULT_BOUNDS_PERKS <- list(lower = c(-20, 0.0001, -1, 0), upper = c(20, 1, 5, 1)) # a, b, gam, lambda
#' @title Perks Model Initializer
#' @description Constructs a PAC S4 object for the Perks survival model.
#' @param params Numeric vector of initial parameter values (default: c(-15, 0.1, 0.7, 0)).
#' @param bounds List with 'lower' and 'upper' numeric vectors for parameter bounds.
#' @return An object of class \code{PAC} for the Perks model.
PerksPAC <- function(params = DEFAULT_PARAMS_PERKS,
                     bounds = DEFAULT_BOUNDS_PERKS) {
  InitPAC("Perks", params, survival_perks, forceofmortality_perks, cumulative_hazard_perks, bounds)
}

# ---- Beard Model ----
DEFAULT_PARAMS_BEARD <- c(-15, 0.1, 0.7) # a, b, gam
DEFAULT_BOUNDS_BEARD <- list(lower = c(-20, 0.0001, -1), upper = c(20, 1, 5)) # a, b, gam
#' @title Beard Model Initializer
#' @description Constructs a PAC S4 object for the Beard survival model.
#' @param params Numeric vector of initial parameter values (default: c(-15, 0.1, 0.7)).
#' @param bounds List with 'lower' and 'upper' numeric vectors for parameter bounds.
#' @return An object of class \code{PAC} for the Beard model.
BeardPAC <- function(params = DEFAULT_PARAMS_BEARD,
                     bounds = DEFAULT_BOUNDS_BEARD) {
  InitPAC("Beard", params, survival_beard, forceofmortality_beard, cumulative_hazard_beard, bounds)
}

# ---- Kannisto Model ----
DEFAULT_PARAMS_KANNISTO <- c(-10, 0.1) # a, b
DEFAULT_BOUNDS_KANNISTO <- list(lower = c(-20, 0.0001), upper = c(20, 1)) # a, b
#' @title Kannisto Model Initializer
#' @description Constructs a PAC S4 object for the Kannisto survival model.
#' @param params Numeric vector of initial parameter values (default: c(-10, 0.1)).
#' @param bounds List with 'lower' and 'upper' numeric vectors for parameter bounds.
#' @return An object of class \code{PAC} for the Kannisto model.
KannistoPAC <- function(params = DEFAULT_PARAMS_KANNISTO,
                        bounds = DEFAULT_BOUNDS_KANNISTO) {
  InitPAC("Kannisto", params, survival_kannisto, forceofmortality_kannisto, cumulative_hazard_kannisto, bounds)
}

# ---- Thatcher Model ----
DEFAULT_PARAMS_THATCHER <- c(-10, 0.1, 0) # a, b, lambda
DEFAULT_BOUNDS_THATCHER <- list(lower = c(-20, 0.0001, 0), upper = c(20, 1, 1)) # a, b, lambda
#' @title Thatcher Model Initializer
#' @description Constructs a PAC S4 object for the Thatcher survival model.
#' @param params Numeric vector of initial parameter values (default: c(-10, 0.1, 0)).
#' @param bounds List with 'lower' and 'upper' numeric vectors for parameter bounds.
#' @return An object of class \code{PAC} for the Thatcher model.
ThatcherPAC <- function(params = DEFAULT_PARAMS_THATCHER,
                        bounds = DEFAULT_BOUNDS_THATCHER) {
  InitPAC("Thatcher", params, survival_thatcher, forceofmortality_thatcher, cumulative_hazard_thatcher, bounds)
}

# ---- High-level formula interface ----

# Map AC string -> constructor
.pac_registry <- list(
  Gompertz  = GompertzPAC,
  Makeham   = MakehamPAC,
  Perks     = PerksPAC,
  Beard     = BeardPAC,
  Kannisto  = KannistoPAC,
  Thatcher  = ThatcherPAC
)

#' Fit a PAC model via a formula interface
#'
#' @param formula A survival formula. Use counting-process syntax:
#'   Surv(birthage, censoredage, DthIndicator) ~ 1
#'   (RHS must be ~ 1 for age-only models.)
#' @param data A data.frame containing the variables in the formula.
#' @param AC Character name of the age-cohort family: one of
#'   names(.pac_registry) e.g. "Gompertz", "Makeham", etc.
#' @param start Optional numeric vector of initial params to override defaults.
#' @param bounds Optional list(lower=..., upper=...) to override defaults.
#' @param patience, tol, verbose Passed through to `fit()`.
#' @return A PACFit S4 object.
pac_fit <- function(formula, data,
                    AC = c("Gompertz","Makeham","Perks","Beard","Kannisto","Thatcher"),
                    start = NULL, bounds = NULL,
                    patience = 500, tol = 1e-6, verbose = FALSE) {
  AC <- match.arg(AC)

  # Build model frame and extract Surv response
  mf <- stats::model.frame(formula, data = data, na.action = na.omit)
  y  <- stats::model.response(mf)

  # Expect counting-process Surv(start, stop, event)
  sType <- attr(y, "type")
  if (!(sType %in% c("counting"))) {
    stop("Use Surv(birthage, censoredage, DthIndicator) with counting-process syntax.")
  }
  birthage      <- y[, 1]
  censoredage   <- y[, 2]
  DthIndicator  <- y[, 3]

  # Age-only dataset expected by your current code
  df_train <- data.frame(
    birthage = as.numeric(birthage),
    censoredage = as.numeric(censoredage),
    DthIndicator = as.integer(DthIndicator)
  )

  # Instantiate the chosen PAC model
  ctor <- .pac_registry[[AC]]
  if (is.null(ctor)) stop("Unknown AC family: ", AC)
  pac_model <- ctor()

  # Optional overrides
  if (!is.null(start))  pac_model@params <- start
  if (!is.null(bounds)) pac_model@bounds <- bounds

  # Build PACFit and fit
  fit_obj <- methods::new("PACFit", model = pac_model, data = list(train = df_train, test = NULL))
  fit_obj <- fit(fit_obj, data_train = df_train, patience = patience, tol = tol, verbose = verbose)
  return(fit_obj)
}

setGeneric("evaluate", function(object, ...) standardGeneric("evaluate"))

#' Predict helper (optional but handy)
#' @param object PACFit
#' @param newdata data.frame with birthage and age columns
#' @param type "survival"|"hazard"|"loglik"
#' @param age_col column name for absolute age at which to evaluate
#' @return numeric vector
predict.PACFit <- function(object, newdata,
                           type = c("survival","hazard","loglik"),
                           age_range = 80:115) {
  # Basic checks
  if (!isTRUE(object@fitted)) stop("PACFit object is not fitted.")
  if (!is.data.frame(newdata)) stop("'newdata' must be a data.frame.")
  type <- match.arg(type)

  ages <- sort(as.numeric(age_range))
  if (any(!is.finite(ages))) stop("'age_range' must be finite numerics.")

  par <- object@model@params
  n   <- nrow(newdata)
  rn  <- rownames(newdata); if (is.null(rn)) rn <- as.character(seq_len(n))

  if (type == "survival") {
    if (!("birthage" %in% names(newdata)))
      stop("When type='survival', newdata must contain a 'birthage' column.")

    ba <- as.numeric(newdata$birthage)
    if (any(!is.finite(ba))) stop("'birthage' must be finite numerics.")

    # Unconditional survival at grid ages and at birth ages
    S_age <- object@model@survival_(par, ages)   # length = |ages|
    S_ba  <- object@model@survival_(par, ba)     # length = n

    # Conditional survival matrix S(a|b) = S(a)/S(b)
    M <- matrix(rep(S_age, each = n), nrow = n)
    M <- sweep(M, 1, S_ba, "/")

    # Ages younger than birth age => S = 1
    for (i in seq_len(n)) {
      younger_cols <- which(ages < ba[i])
      if (length(younger_cols)) M[i, younger_cols] <- 1
    }

    M[!is.finite(M)] <- NA_real_
    M <- pmin(pmax(M, 0), 1)
    colnames(M) <- as.character(ages)
    rownames(M) <- rn
    return(M)
  }

  if (type == "hazard") {
    mu_age <- object@model@mu_(par, ages)        # length = |ages|
    M <- matrix(rep(mu_age, each = n), nrow = n)
    M[!is.finite(M)] <- NA_real_
    colnames(M) <- as.character(ages)
    rownames(M) <- rn
    return(M)
  }

  # type == "loglik" : per-individual log-likelihood contribution
  req <- c("birthage","censoredage","DthIndicator")
  missing_cols <- setdiff(req, names(newdata))
  if (length(missing_cols))
    stop("When type='loglik', newdata must contain columns: ",
         paste(req, collapse = ", "), ". Missing: ",
         paste(missing_cols, collapse = ", "))

  ba  <- as.numeric(newdata$birthage)
  ca  <- as.numeric(newdata$censoredage)
  di  <- as.integer(newdata$DthIndicator)

  if (any(!is.finite(ba)) || any(!is.finite(ca)) || any(!is.finite(di)))
    stop("birthage, censoredage, and DthIndicator must be finite (and integer for DthIndicator).")

  ll_vec <- logllh(object@model, par = par, x = ba, r = ca, i = di)
  names(ll_vec) <- rn
  return(ll_vec)
}

#' Evaluate a fitted PAC model on a dataset (incl. predict-based IBS)
#'
#' @param object Fitted PACFit object.
#' @param newdata data.frame with columns birthage, censoredage, DthIndicator.
#' @param metrics Character vector among:
#'   c("AIC","loglik_sum","loglik_vec","IBS").
#' @param ibs_method "predict" (default; masking-only per your rules) or "ipcw" (uses BS()).
#' @param age_range Integer/numeric vector of absolute ages for IBS grid (predict-based).
#' @param normalize_IBS If TRUE, return mean squared error (else sum).
#' @param surv_info Optional (only for ibs_method="ipcw").
#' @param surv_from "newdata" or "train" (only for ibs_method="ipcw").
#' @param data_name Optional cache key for empirical_survival (only for ibs_method="ipcw").
#' @return A named list of requested metrics. For IBS (predict), also returns IBS_sum and IBS_by_age.
evaluate.PACFit <- function(object, newdata,
                            metrics = c("AIC","loglik_sum","loglik_vec","IBS"),
                            ibs_method = c("predict","ipcw"),
                            age_range = 80:115,
                            surv_info = NULL,
                            surv_from = c("newdata","train"),
                            data_name = NULL) {
  if (!isTRUE(object@fitted)) stop("PACFit object is not fitted.")
  if (!is.data.frame(newdata)) stop("'newdata' must be a data.frame.")
  req_cols <- c("birthage","censoredage","DthIndicator")
  miss <- setdiff(req_cols, names(newdata))
  if (length(miss)) stop("Missing required columns in newdata: ", paste(miss, collapse = ", "))

  ibs_method <- match.arg(ibs_method)
  surv_from  <- match.arg(surv_from)
  out <- list()

  if ("AIC" %in% metrics) {
    out$AIC <- tryCatch(AIC(object), error = function(e) NA_real_)
  }

  if ("loglik_vec" %in% metrics || "loglik_sum" %in% metrics) {
    ll_vec <- tryCatch(
      get_logllh(object@model, data_train = newdata, par = object@model@params),
      error = function(e) rep(NA_real_, nrow(newdata))
    )
    if ("loglik_vec" %in% metrics) out$loglik_vec <- ll_vec
    if ("loglik_sum" %in% metrics) out$loglik_sum <- sum(ll_vec)
  }

  if ("IBS" %in% metrics) {
    if (ibs_method == "predict") {
      # ===== Predict-based IBS (masking rules) =====
      ages <- sort(as.numeric(age_range))
      n <- nrow(newdata); m <- length(ages)

      # Predicted conditional survival S_pred(i, x) = S(x)/S(birthage_i)
      S_pred <- predict.PACFit(object, newdata, type = "survival", age_range = ages)  # n x m

      # Broadcast inputs
      CA  <- matrix(as.numeric(newdata$censoredage),  n, m)
      DI  <- matrix(as.integer(newdata$DthIndicator), n, m)
      AGE <- matrix(rep(ages, each = n), n, m)

      # Empirical survival (your rules):
      # S_emp = 0 if x <= censoredage & D==1; 1 if x < censoredage; NA otherwise
      S_emp <- ifelse(AGE <= CA & DI == 1L, 0,
                      ifelse(AGE < CA, 1, 0))

      # Weights: w = 0 if x > censoredage & D==0; 1 otherwise
      w <- ifelse(AGE > CA & DI == 0L, 0, 1)

      # Squared error with masking
      diff2 <- (S_pred - S_emp)^2
      diff2[!is.finite(diff2)] <- NA_real_
      contrib <- diff2 * w

      # Overall IBS (mean over weighted elements if normalize_IBS=TRUE)
      denom_total <- sum(w, na.rm = TRUE)
      IBS_sum     <- sum(contrib, na.rm = TRUE)
      IBS_mean    <- IBS_sum / max(1, denom_total)

      # ----- Age-weighted IBS_by_age -----
      # Exposure (how many weighted elements contribute) at each age
      denom_age   <- colSums(w, na.rm = TRUE) # length m
      by_age_mean <- colSums(contrib, na.rm = TRUE) / pmax(1, denom_age)

      # Weight the per-age means by exposure share so they sum to IBS (when normalized)
      weights_age <- denom_age / max(1, denom_total) # sum(weights_age) == 1
      IBS_part_age  <- by_age_mean * weights_age # sum == IBS_mean
      # Unnormalized: contributions per age (sum equals IBS_sum)
      IBS_by_age  <- by_age_mean # equals colSums(contrib)

      names(IBS_by_age) <- as.character(ages)

      #out$S_emp <- S_emp
      #out$S_pred <- S_pred
      #out$w <- w

      out$IBS <- IBS_mean
      out$IBS_part_age <- IBS_part_age
      out$IBS_by_age <- IBS_by_age

    } else {
      # ===== IPCW/KM-based IBS (legacy BS()) =====
      if (is.null(surv_info)) {
        src <- switch(
          surv_from,
          newdata = newdata,
          train   = if (!is.null(object@data) && !is.null(object@data$train)) object@data$train else newdata
        )
        if (is.null(data_name)) {
          data_name <- paste0("eval_", if (!is.null(newdata$data)) unique(newdata$data)[1] else "newdata")
        }
        surv_info <- tryCatch(empirical_survival(src, data_name = data_name), error = function(e) NULL)
      }
      out$IBS <- tryCatch({
        if (is.null(surv_info)) stop("surv_info unavailable")
        BS(object, data_valid = newdata, Surv_info = surv_info)
      }, error = function(e) NA_real_)
      # No IBS_by_age from IPCW path
    }
  }

  out
}

setMethod("predict", "PACFit", predict.PACFit)
setMethod("evaluate", "PACFit", evaluate.PACFit)

# =========================
# 3. S4 Class Definitions
# =========================

setClassUnion("data.frameOrNULL", c("data.frame", "NULL"))

# ---- 3.1 MortalityModel (Parent) ----
# S4 class for basic mortality model
setClass(
  "MortalityModel",
  slots = list(
    data = "list",
    data_train = "data.frameOrNULL",
    data_test = "data.frameOrNULL"
  )
)

# Constructor for MortalityModel
MortalityModel <- function(data = NULL, data_train = NULL, data_test = NULL) {
  if (is.data.frame(data)) {
    data_train <- data
    data_test <- NULL
    data <- list(train = data_train, test = data_test)
  }

  if (is.null(data)){
    data <- list(train = data_train, test = data_test)
  }

  new("MortalityModel",
      data = data,
      data_train = data$train,
      data_test = data$test
  )
}
# Show method for MortalityModel
setMethod("show", "MortalityModel", function(object) {
  if (is.null(object@data_train)) {
    cat("Empty Training data\n")
  } else cat("Training data size:", nrow(object@data_train), "\n")
  if (is.null(object@data_test)) {
    cat("Empty Test data\n")
  } else cat("Test data size:", nrow(object@data_test), "\n")
})

# Generics for IBS and logScore
setGeneric("getIBS", function(object) standardGeneric("getIBS"))
setGeneric("getlogScore", function(object) standardGeneric("getlogScore"))

# ---- 3.2 STModel (Survival Tree) ----
# S4 class for survival tree model
setOldClass("rpart")
setClass(
  "STModel",
  slots = list(
    IMM = "MortalityModel",
    model = "rpart",
    tnodes = "character"
  )
)
# Helper to fit survival tree
get_tree <- function(formula, data) {
  # data <- data %>% select(
  #   birthage, censoredage, DthIndicator,
  #   ADLCount, InterviewerRateHealth, Gender,
  #   LanguageAbility, CalculationAbility,
  #   waves
  # )
  data <- as.data.frame(data)
  # formula <- Surv(birthage, censoredage, DthIndicator) ~
  #   ADLCount + InterviewerRateHealth + Gender +
  #   LanguageAbility + CalculationAbility + waves
  LTRCART(
    formula,
    data = data
  )
}
# Constructor for STModel
STModel <- function(formula, data = NULL, data_train = NULL, data_test = NULL, IMM=NULL) {
  if (is.null(IMM)) {
    # If IMM is not provided, create a new MortalityModel
    IMM <- MortalityModel(data = data, data_train = data_train, data_test = data_test)
  }
  train_copy <- IMM@data_train
  test_copy <- IMM@data_test
  tree <- get_tree(formula, train_copy)
  train_copy$node <- as.vector(tree$where)
  tnodes <- train_copy$node %>% factor() %>% levels()
  test_copy$group <- predict(tree %>% as.party(), newdata = test_copy, type = "node")
  IMM@data <- list(train = train_copy, test = test_copy)
  IMM@data_train <- train_copy
  IMM@data_test <- test_copy
  new("STModel", IMM = IMM, model = tree, tnodes = tnodes)
}
# Show method for STModel
setMethod("show", "STModel", function(object) {
  cat("Training data size:", nrow(object@IMM@data_train), "\n")
  cat("Test data size:", nrow(object@IMM@data_test), "\n")
  cat("Terminal nodes:", paste(object@tnodes, collapse = ", "), "\n")
})

# ---- 3.3 BaselineModel ----
# S4 class for baseline parametric model
setClass(
  "BaselineModel",
  slots = list(
    IMM = "MortalityModel",
    model_fit = "PACFit"
  )
)
# Constructor for BaselineModel
BaselineModel <- function(data = NULL, data_train = NULL, data_test = NULL, AC=BeardPAC()) {
  IMM <- MortalityModel(data = data, data_train = data_train, data_test = data_test)
  set.seed(5346615)
  pac_fit_obj <- new("PACFit", model = AC, data = IMM@data)
  pac_fit_obj <- fit(pac_fit_obj, IMM@data_train, patience = 500)
  new("BaselineModel", IMM = IMM, model_fit = pac_fit_obj)
}
# Show method for BaselineModel
setMethod("show", "BaselineModel", function(object) {
  cat("Training data size:", nrow(object@IMM@data_train), "\n")
  cat("Test data size:", nrow(object@IMM@data_test), "\n")
  cat("Model fit parameters:", object@model_fit@model@params, "\n")
})
# IBS and logScore methods for BaselineModel
setMethod("getIBS", "BaselineModel", function(object) {
  BS(object@model_fit, object@IMM@data_test, object@IMM@Surv_info)
})
setMethod("getlogScore", "BaselineModel", function(object) {
  sum(get_logllh(object@model_fit@model, object@IMM@data_test))
})

setMethod("predict", "BaselineModel", function(object, newdata=NULL, type = "survival") {
  if (type != "survival") {
    stop("Only 'survival' type is supported.")
  }
  if (is.null(newdata)) {
    newdata <- object@IMM@data_test
  }
  # Predict survival probabilities
  pac <- object@model_fit@model
  S <- pac %>% survival(newdata$censoredage)
  S_0 <- pac %>% survival(newdata$birthage)
  pred_probs <- S / S_0
  return(pred_probs)
})

# ---- 3.4 STPModel (Survival Tree Partitioning) ----
# S4 class for partitioned tree model
setClass(
  "STPModel",
  slots = list(
    STModel = "STModel",
    AC = "PAC",
    par_train = "matrix"
  )
)
# Constructor for STPModel
STPModel <- function(data = NULL, data_train = NULL, data_test = NULL, AC = BeardPAC(), ST = NULL) {
  if (is.null(ST)) {
    # If ST is not provided, create a new STModel
    ST <- STModel(data = data, data_train = data_train, data_test = data_test)
  }
  par_train <- c()
  for (nodei in ST@tnodes) {
    set.seed(5346615)
    pac_fit_obj <- new("PACFit", model = AC, data = ST@IMM@data)
    pac_fit_obj = fit(pac_fit_obj, ST@IMM@data_train %>% filter(node == nodei), patience = 500)
    par_train <- par_train %>% rbind(pac_fit_obj@model@params)
  }
  new("STPModel", STModel = ST, AC = AC, par_train = par_train)
}
# Show method for STPModel
setMethod("show", "STPModel", function(object) {
  cat("Training data size:", nrow(object@STModel@IMM@data_train), "\n")
  cat("Test data size:", nrow(object@STModel@IMM@data_test), "\n")
  cat("Terminal nodes:", paste(object@STModel@tnodes, collapse = ", "), "\n")
})
# IBS and logScore methods for STPModel
setMethod("getIBS", "STPModel", function(object) {
  tnodes = object@STModel@tnodes
  test_copy = object@STModel@IMM@data_test
  sum_count = 0
  for (node_num in seq_along(tnodes)) {
    sub_test_copy <- test_copy %>% filter(test_copy$group == tnodes[node_num])
    PACfit <- new("PACFit", model = object@AC, data = object@STModel@IMM@data)
    PACfit@model@params <- object@par_train[node_num, ]
    PACfit@fitted <- TRUE
    BS_node <- BS(PACfit, sub_test_copy, object@STModel@IMM@Surv_info)
    sum_count = sum_count + nrow(sub_test_copy) * BS_node
  }
  return(sum_count / nrow(test_copy))
})
setMethod("getlogScore", "STPModel", function(object) {
  logllh <- 0
  tnodes = object@STModel@tnodes
  test_copy = object@STModel@IMM@data_test
  for (node_num in seq_along(tnodes)) {
    sub_test_copy <- test_copy %>% filter(test_copy$group == tnodes[node_num])
    PACfit <- new("PACFit", model = object@AC, data = object@STModel@IMM@data)
    PACfit@model@params <- object@par_train[node_num, ]
    PACfit@fitted <- TRUE
    logllh_node <- sum(get_logllh(PACfit@model, sub_test_copy))
    logllh <- logllh + logllh_node
  }
  return(logllh)
})
# setMethod("predict", "STPModel", function(object, newdata = NULL, type = "survival") {
#   if (type != "survival") {
#     stop("Only 'survival' type is supported.")
#   }
#   if (is.null(newdata)) {
#     newdata <- object@STModel@IMM@data_test
#   }
#   else{
#     newdata$group <- predict(tree %>% as.party(), newdata = newdata, type = "node")
#   }
#   # Predict survival probabilities for each node
#   df_S <- data.frame()
#   for (nodei in object@STModel@tnodes) {
#     pac <- object@AC
#     pac@params <- object@par_train[match(nodei, object@STModel@tnodes), ]
#     S <- pac %>% survival(newdata$censoredage)
#     S_0 <- pac %>% survival(newdata$birthage)
#     df_S <- df_S %>% rbind(S/S_0)
#   }
#   df_S <- t(df_S)
#   colnames(df_S) <- object@STModel@tnodes
#   # get individual survival given predicted group using vectorized approach
#   group_idx <- match(newdata$group, object@STModel@tnodes)
#   pred_probs <- df_S[cbind(seq_len(nrow(newdata)), group_idx)]
#
#   return(pred_probs)
# })

# ---- 3.5 MortalityModel_FillNA ----
# S4 class for model with missing values filled
setClass(
  "MortalityModel_FillNA",
  slots = list(
    IMM = "MortalityModel",
    train_fillna = "data.frame",
    test_fillna = "data.frame"
  )
)
# Constructor for MortalityModel_FillNA
MortalityModel_FillNA <- function(data = NULL, data_train = NULL, data_test = NULL) {
  IMM <- MortalityModel(data = data, data_train = data_train, data_test = data_test)
  train_fillna <- IMM@data_train
  # Fill NAs with "Missing" for categorical variables
  for (i in 5:ncol(train_fillna)) {
    train_fillna[[i]] <- train_fillna[[i]] %>%
      as.character() %>% replace_na("Missing") %>% as.factor()
  }
  test_fillna <- IMM@data_test
  for (i in 5:ncol(test_fillna)) {
    test_fillna[[i]] <- test_fillna[[i]] %>%
      as.character() %>% replace_na("Missing") %>% as.factor()
  }
  new("MortalityModel_FillNA",
      IMM = IMM,
      train_fillna = train_fillna,
      test_fillna = test_fillna
  )
}
# Show method for MortalityModel_FillNA
setMethod("show", "MortalityModel_FillNA", function(object) {
  cat("Training data size:", nrow(object@train_fillna), "\n")
  cat("Test data size:", nrow(object@test_fillna), "\n")
})

# ---- 3.6 MTPModel ----
# S4 class for model-based recursive partitioning (mob)
setOldClass("modelparty")
setClass(
  "MTPModel",
  slots = list(
    IMM_filled = "MortalityModel_FillNA",
    formula = "formula",
    mobfit = "modelparty",
    mob_coef = "matrix",
    mob_tnodes_test = "numeric"
  )
)
# Constructor for MTPModel
MTPModel <- function(formula, data = NULL, data_train = NULL, data_test = NULL) {
  IMM_filled <- MortalityModel_FillNA(data = data, data_train = data_train, data_test = data_test)
  # Define partitioning formula
  # mobformula <- Surv(birthage, censoredage, DthIndicator) ~ 1 |
  #   ADLCount + InterviewerRateHealth + Gender +
  #   LanguageAbility + Illness + GeneralAbility + Education +
  #   SmokeEver + CalculationAbility +
  #   ReactionAbility + MemorisingAbility + DrinkEver +
  #   incomesource + SelfratedHealth
  # if (data_name == "doverall") {
  #   mobformula <- Surv(birthage, censoredage, DthIndicator) ~ 1 |
  #     ADLCount + InterviewerRateHealth + Gender +
  #     LanguageAbility + Illness + GeneralAbility + Education +
  #     SmokeEver + CalculationAbility +
  #     ReactionAbility + MemorisingAbility + DrinkEver +
  #     incomesource + SelfratedHealth + waves
  # }
  # Custom fit function for mob
  gpreg <- function(y, x, start = NULL, weights = NULL, offset = NULL, ...) {
    flexsurvreg(y ~ 0 + x, weights = weights, dist = "gompertz", ...)
  }
  # Fit mob model
  mobfit <- mob(
    formula,
    data = IMM_filled@train_fillna,
    fit = gpreg,
    control = mob_control(minsize = nrow(IMM_filled@train_fillna) / 50, maxdepth = 10)
  )
  mob_coef <- coef(mobfit)
  mob_tnodes_test <- predict(mobfit, IMM_filled@test_fillna, type = "node")
  # If only one node, fallback to baseline
  if(length(unique(mob_tnodes_test))==1){
    IMM <- IMM_filled@IMM
    GompertzFit <- new("PACFit", model = GompertzPAC(), data = IMM@data)
    GompertzFit@model@params <- c(mob_coef[2], mob_coef[1])
    GompertzFit@fitted <- TRUE
    new("BaselineModel", IMM = IMM, model_fit = GompertzFit)
  } else {
    new("MTPModel",
        IMM_filled = IMM_filled,
        formula = formula,
        mobfit = mobfit,
        mob_coef = mob_coef,
        mob_tnodes_test = mob_tnodes_test
    )
  }
}
# Show method for MTPModel
setMethod("show", "MTPModel", function(object) {
  cat("Training data size:", nrow(object@IMM_filled@train_fillna), "\n")
  cat("Test data size:", nrow(object@IMM_filled@test_fillna), "\n")
  cat("Terminal nodes in MTP model:", nrow(object@mob_coef), "\n")
})
# IBS and logScore methods for MTPModel
setMethod("getIBS", "MTPModel", function(object) {
  tnodes = object@mob_coef %>% rownames()
  test_copy <- object@IMM_filled@test_fillna
  sum_count <- 0
  for (i in seq_along(tnodes)) {
    sub_test_copy <- test_copy %>% filter(object@mob_tnodes_test == tnodes[i])
    pari <- object@mob_coef[match(tnodes[i], rownames(object@mob_coef)), ]
    pari <- pari[2:1]
    PACfit <- new("PACFit", model = GompertzPAC(), data = object@IMM_filled@IMM@data)
    PACfit@model@params <- pari
    PACfit@fitted <- TRUE
    BS_node <- BS(PACfit, sub_test_copy, object@IMM_filled@IMM@Surv_info)
    sum_count <- sum_count + nrow(sub_test_copy) * BS_node
  }
  ibs_mob <- sum_count / nrow(test_copy)
  return(ibs_mob)
})
setMethod("getlogScore","MTPModel", function(object) {
  logllh <- 0
  tnodes = object@mob_coef %>% rownames()
  test_copy <- object@IMM_filled@test_fillna
  for (i in seq_along(tnodes)) {
    sub_test_copy <- test_copy %>% filter(object@mob_tnodes_test == tnodes[i])
    pari <- object@mob_coef[match(tnodes[i], rownames(object@mob_coef)), ]
    pari <- pari[2:1]
    PACfit <- new("PACFit", model = GompertzPAC(), data = object@IMM_filled@IMM@data)
    PACfit@model@params <- pari
    PACfit@fitted <- TRUE
    logllh_node <- sum(get_logllh(PACfit@model, sub_test_copy))
    logllh <- logllh + logllh_node
  }
  return(logllh)
})
# setMethod("predict", "MTPModel", function(object, newdata = NULL, type = "survival") {
#   if (type != "survival") {
#     stop("Only 'survival' type is supported.")
#   }
#   if (is.null(newdata)) {
#     newdata <- object@IMM_filled@test_fillna
#     newdata$group <- object@mob_tnodes_test
#   }
#   else{
#     newdata$group <- predict(mobfit, newdata, type = "node")
#   }
#   tnodes = object@mob_coef %>% rownames()
#   mob_coef <- object@mob_coef[,2:1] # switch order to match Gompertz parameters
#   # Predict survival probabilities for each node
#   df_S <- data.frame()
#   for (nodei in tnodes) {
#     pac <- GompertzPAC()
#     pac@params <- mob_coef[match(nodei, tnodes), ]
#     S <- pac %>% survival(newdata$censoredage)
#     S_0 <- pac %>% survival(newdata$birthage)
#     df_S <- df_S %>% rbind(S/S_0)
#   }
#   df_S <- t(df_S)
#   colnames(df_S) <- tnodes
#   # get individual survival given predicted group using vectorized approach
#   group_idx <- match(newdata$group, tnodes)
#   pred_probs <- df_S[cbind(seq_len(nrow(newdata)), group_idx)]
#
#   return(pred_probs)
# })

# ---- 3.7 GPHModel ----
# S4 class for Gompertz proportional hazards model
setOldClass("flexsurvreg")
setClass(
  "GPHModel",
  slots = list(
    IMM_filled = "MortalityModel_FillNA",
    formula = "formula",
    gpfit = "flexsurvreg",
    gpfit_pred = "numeric",
    gpfit_shape = "numeric"
  )
)
# Constructor for GPHModel
GPHModel <- function(formula, data = NULL, data_train = NULL, data_test = NULL) {
  IMM_filled <- MortalityModel_FillNA(data = data, data_train = data_train, data_test = data_test)
  set.seed(5346615)
  # gpformula <- Surv(birthage, censoredage, DthIndicator) ~
  #   ADLCount + InterviewerRateHealth + Gender +
  #   LanguageAbility + Illness + GeneralAbility + Education +
  #   SmokeEver + CalculationAbility +
  #   ReactionAbility + MemorisingAbility + DrinkEver +
  #   incomesource + SelfratedHealth
  # if (data_name == "doverall") {
  #   gpformula <- update(gpformula, . ~ . + waves)
  # }
  gpfit <- flexsurvreg(formula, data = IMM_filled@train_fillna, dist = "gompertz")
  gpfit_pred <- gpfit %>% predict(IMM_filled@test_fillna, type = "lp")
  gpfit_pred <- gpfit_pred$.pred_link
  gpfit_pred <- log(gpfit_pred)
  gpfit_shape <- gpfit$coefficients[1]
  new("GPHModel",
      IMM_filled = IMM_filled,
      formula = formula,
      gpfit = gpfit,
      gpfit_pred = gpfit_pred,
      gpfit_shape = gpfit_shape
  )
}
# Show method for GPHModel
setMethod("show", "GPHModel", function(object) {
  cat("Training data size:", nrow(object@IMM_filled@train_fillna), "\n")
  cat("Test data size:", nrow(object@IMM_filled@test_fillna), "\n")
  cat("Shape parameter:", object@gpfit_shape, "\n")
})
# IBS and logScore methods for GPHModel
setMethod("getIBS", "GPHModel", function(object) {
  test_fillna <- object@IMM_filled@test_fillna
  Surv_info <- object@IMM_filled@IMM@Surv_info
  ibs_recorder <- rep(0, nrow(test_fillna))
  PACfit <- new("PACFit", model = GompertzPAC(), data = object@IMM_filled@IMM@data)
  PACfit@fitted <- TRUE
  for (i in seq_len(nrow(test_fillna))) {
    PACfit@model@params <- c(object@gpfit_pred[i], object@gpfit_shape)
    ibs_recorder[i] <- BS(PACfit, test_fillna[i, ], Surv_info = Surv_info)
  }
  ibs_gph <- mean(ibs_recorder)
  return(ibs_gph)
})
setMethod("getlogScore", "GPHModel", function(object) {
  logllh = 0
  test_fillna <- object@IMM_filled@test_fillna
  Surv_info <- object@IMM_filled@IMM@Surv_info
  PACfit <- new("PACFit", model = GompertzPAC(), data = object@IMM_filled@IMM@data)
  PACfit@fitted <- TRUE
  for (i in seq_len(nrow(test_fillna))) {
    PACfit@model@params <- c(object@gpfit_pred[i], object@gpfit_shape)
    logllh = logllh + get_logllh(PACfit@model, test_fillna[i,])
  }
  return(logllh)
})
setMethod("predict", "GPHModel", function(object, newdata = NULL, type = "survival") {
  if (type != "survival") {
    stop("Only 'survival' type is supported.")
  }
  if (is.null(newdata)) {
    newdata <- object@IMM_filled@test_fillna
  }
  # Predict survival probabilities
  getS <- function(alpha, ca, ba){
    pac <- GompertzPAC()
    pac@params <- c(alpha, object@gpfit_shape)
    S <- pac %>% survival(ca)
    S_0 <- pac %>% survival(ba)
    return(S / S_0)
  }

  pred_probs <- mapply(getS, object@gpfit_pred, newdata$censoredage, newdata$birthage)

  return(pred_probs)
})

# =========================
# 4. Utility Functions
# =========================

# Log-likelihood extractor for flexsurvreg
logLik.flexsurvreg <- function(object, ...) {
  structure(object$loglik, df = object$npars, class = "logLik")
}
# Empirical estimating function for flexsurvreg (Gompertz only)
estfun.flexsurvreg <- function(object, ...) {
  if (object$dlist$name == "gompertz") {
    Y <- object$data$Y[, 1:3]
    Li <- Y[, 1]
    Ci <- Y[, 2]
    di <- Y[, 3]
    a <- object$coefficients[1]
    log_b <- object$coefficients[2]
    b <- exp(log_b)
    est_shape <- di * Ci - b / (a^2) * (exp(a * Ci) * (a * Ci - 1) - exp(a * Li) * (a * Li - 1))
    est_rate <- di / b - (exp(a * Ci) - exp(a * Li)) / a
    return(cbind(est_shape, est_rate))
  }
}

# =========================
# Unified formula-first fitters
# =========================

# Helper: map AC family input -> PAC object
.AC_registry <- list(
  Gompertz  = GompertzPAC,
  Makeham   = MakehamPAC,
  Perks     = PerksPAC,
  Beard     = BeardPAC,
  Kannisto  = KannistoPAC,
  Thatcher  = ThatcherPAC
)
AC_from <- function(AC = "Beard") {
  if (inherits(AC, "PAC")) return(AC)
  if (is.character(AC)) {
    ctor <- .AC_registry[[AC]]
    if (is.null(ctor)) stop("Unknown AC family: ", AC)
    return(ctor())
  }
  if (is.function(AC)) return(AC())
  stop("AC must be a PAC object, a family name, or a family constructor.")
}

# Small guard: baseline requires ~ 1
.ensure_age_only <- function(formula) {
  tl <- attr(stats::terms(formula), "term.labels")
  if (length(tl) > 0) {
    warning("Baseline model are age-only; RHS covariates will be ignored.")
  }
}

# 1) Baseline age-only parametric model (PAC)
baseline_fit <- function(formula,
                         data = NULL,
                         data_train = NULL,
                         data_test = NULL,
                         AC = "Beard",
                         patience = 500, tol = 1e-6, verbose = FALSE) {
  .ensure_age_only(formula)
  # Reuse your formula-based PAC fitter
  # (expects Surv(birthage, censoredage, DthIndicator) ~ 1)
  pf <- pac_fit(formula, data = data_train,
                AC = if (inherits(AC, "PAC")) AC@name else AC,
                patience = patience, tol = tol, verbose = verbose)
  IMM <- MortalityModel(data = data)
  methods::new("BaselineModel", IMM = IMM, model_fit = pf)
}

# 2) Survival Tree (LTRCART)
st_fit <- function(formula,
                   data = NULL,
                   data_train = NULL,
                   data_test = NULL) {
  STModel(formula = formula, data = data)
}

# 3) Survival Tree Partitioning (tree+PAC per node)
stp_fit <- function(formula,
                    data = NULL,
                    data_train = NULL,
                    data_test = NULL,
                    AC = "Beard") {
  st <- STModel(formula = formula, data = data)
  STPModel(ST = st, AC = AC_from(AC))
}

# 4) Model-based recursive partitioning (mob + Gompertz)
mtp_fit <- function(formula,
                    data = NULL,
                    data_train = NULL,
                    data_test = NULL) {
  MTPModel(formula = formula, data = data)
}

# 5) Gompertz proportional hazards (flexsurvreg)
gph_fit <- function(formula,
                    data = NULL,
                    data_train = NULL,
                    data_test = NULL) {
  GPHModel(formula = formula, data = data)
}

# 6) One front door for everything
mort_fit <- function(model = c("baseline","st","stp","mtp","gph"),
                     formula,
                     data = NULL,
                     data_train = NULL,
                     data_test = NULL,
                     ...) {
  if (is.data.frame(data)) {
    data_train <- data
    data_test <- NULL
    data <- list(train = data_train, test = data_test)
  }

  if (is.null(data)){
    data <- list(train = data_train, test = data_test)
  }

  model <- match.arg(model)
  switch(model,
         baseline = baseline_fit(formula, data, data_train, data_test, ...),
         st       = st_fit(formula, data, data_train, data_test),
         stp      = stp_fit(formula, data, data_train, data_test, ...),
         mtp      = mtp_fit(formula, data, data_train, data_test),
         gph      = gph_fit(formula, data, data_train, data_test),
         stop("Unknown model type.")
  )
}


# ============================================================
# Shared helpers
# ============================================================

# Predict-based IBS from a precomputed S_pred matrix (n x |ages|)
.ibs_from_Spred <- function(newdata, S_pred, ages, normalize = TRUE) {
  n <- nrow(newdata); m <- length(ages)
  CA  <- matrix(as.numeric(newdata$censoredage),  n, m)
  DI  <- matrix(as.integer(newdata$DthIndicator), n, m)
  AGE <- matrix(rep(ages, each = n), n, m)

  # S_emp: 0 if x <= CA & death; 1 if x < CA; NA otherwise
  S_emp <- ifelse(AGE <= CA & DI == 1L, 0,
                  ifelse(AGE < CA, 1, NA_real_))
  # weights: 0 if x > CA & censored; 1 otherwise
  w <- ifelse(AGE > CA & DI == 0L, 0, 1)

  diff2 <- (S_pred - S_emp)^2
  diff2[!is.finite(diff2)] <- NA_real_

  contrib <- diff2 * w
  denom_total <- sum(w, na.rm = TRUE)
  IBS_sum     <- sum(contrib, na.rm = TRUE)
  IBS_mean    <- if (normalize) IBS_sum / max(1, denom_total) else IBS_sum

  # Age-weighted IBS_by_age (sums to IBS when normalized)
  denom_age   <- colSums(w, na.rm = TRUE)
  by_age_mean <- colSums(contrib, na.rm = TRUE) / pmax(1, denom_age)
  if (normalize) {
    weights_age <- denom_age / max(1, denom_total)
    IBS_by_age  <- by_age_mean * weights_age
  } else {
    IBS_by_age  <- by_age_mean * denom_age
  }
  names(IBS_by_age) <- as.character(ages)

  list(IBS = IBS_mean, IBS_by_age = IBS_by_age)
}

# ============================================================
# Common evaluate() generic
# ============================================================
setGeneric("evaluate", function(object, newdata, ...) standardGeneric("evaluate"))

# ============================================================
# BaselineModel: predict/evaluate (delegate to contained PACFit)
# ============================================================

setMethod("predict", "BaselineModel",
          function(object, newdata = NULL,
                   type = c("survival","hazard","loglik"),
                   age_range = 80:115) {
            type <- match.arg(type)
            if (is.null(newdata)) newdata <- object@IMM@data_test
            predict.PACFit(object@model_fit, newdata = newdata, type = type, age_range = age_range)
          })

setMethod("evaluate", "BaselineModel",
          function(object, newdata = NULL,
                   metrics = c("AIC","loglik_sum","loglik_vec","IBS"),
                   ibs_method = c("predict","ipcw"),
                   age_range = 80:115,
                   normalize_IBS = TRUE,
                   ...) {
            if (is.null(newdata)) newdata <- object@IMM@data_test
            ibs_method <- match.arg(ibs_method)
            # reuse evaluate.PACFit
            evaluate.PACFit(object@model_fit, newdata = newdata, metrics = metrics,
                            ibs_method = ibs_method, age_range = age_range,
                            normalize_IBS = normalize_IBS, ...)
          })

# ============================================================
# STPModel: predict/evaluate (per-node PAC parameters)
# ============================================================

setMethod("predict", "STPModel",
          function(object, newdata = NULL,
                   type = c("survival","hazard","loglik", "group", "par"),
                   age_range = 80:115) {
            type <- match.arg(type)
            ages <- sort(as.numeric(age_range))
            if (is.null(newdata)) {
              newdata <- object@STModel@IMM@data_test
              if (is.null(newdata$group)) {
                newdata$group <- predict(object@STModel@model %>% partykit::as.party(),
                                         newdata = newdata, type = "node")
              }
            } else {
              newdata$group <- predict(object@STModel@model %>% partykit::as.party(),
                                       newdata = newdata, type = "node")
            }

            tnodes <- object@STModel@tnodes
            # Precompute per-node functions at 'ages'
            if (type %in% c("survival","hazard")) {
              S_or_mu <- matrix(NA_real_, nrow(newdata), length(ages))
              for (nodei in tnodes) {
                idx <- which(newdata$group == nodei)
                if (!length(idx)) next
                pac <- object@AC
                pac@params <- object@par_train[match(nodei, tnodes), ]
                if (type == "survival") {
                  S_age <- pac@survival_(pac@params, ages)             # |ages|
                  S_ba  <- pac@survival_(pac@params, newdata$birthage[idx])
                  M     <- matrix(rep(S_age, each = length(idx)), nrow = length(idx))
                  M     <- sweep(M, 1, S_ba, "/")
                  # ages < birthage -> 1
                  for (k in seq_along(idx)) {
                    younger <- which(ages < newdata$birthage[idx[k]])
                    if (length(younger)) M[k, younger] <- 1
                  }
                  S_or_mu[idx, ] <- M
                } else {
                  mu_age <- pac@mu_(pac@params, ages)
                  S_or_mu[idx, ] <- matrix(rep(mu_age, each = length(idx)), nrow = length(idx))
                }
              }
              colnames(S_or_mu) <- as.character(ages)
              return(S_or_mu)
            }

            # type == "loglik"
            # Sum per-row log-likelihood using node-specific PAC
            ll <- rep(NA_real_, nrow(newdata))
            for (nodei in tnodes) {
              idx <- which(newdata$group == nodei)
              if (!length(idx)) next
              pac <- object@AC
              pac@params <- object@par_train[match(nodei, tnodes), ]
              ll[idx] <- logllh(pac,
                                par = pac@params,
                                x = newdata$birthage[idx],
                                r = newdata$censoredage[idx],
                                i = newdata$DthIndicator[idx])
            }

            if (type == "group") return( newdata$group)
            if (type == "par")   return( object@par_train[match(newdata$group, tnodes), , drop = FALSE])

            names(ll) <- rownames(newdata)
            ll
          })



setMethod("evaluate", "STPModel",
          function(object, newdata = NULL,
                   metrics = c("AIC","loglik_sum","loglik_vec","IBS"),
                   age_range = 80:115, normalize_IBS = TRUE, ...) {
            if (is.null(newdata)) {
              newdata <- object@STModel@IMM@data_test
              if (is.null(newdata$group)) {
                newdata$group <- predict(object@STModel@model %>% partykit::as.party(),
                                         newdata = newdata, type = "node")
              }
            }
            ages <- sort(as.numeric(age_range))
            out <- list()

            # AIC not defined for STP (no single parametric likelihood)
            if ("AIC" %in% metrics) out$AIC <- NA_real_

            # loglik
            if ("loglik_vec" %in% metrics || "loglik_sum" %in% metrics) {
              ll_vec <- predict(object, newdata, type = "loglik")
              if ("loglik_vec" %in% metrics) out$loglik_vec <- ll_vec
              if ("loglik_sum" %in% metrics) out$loglik_sum <- sum(ll_vec, na.rm = TRUE)
            }

            # IBS via predict-based method

            if ("IBS" %in% metrics) {
              S_pred <- predict(object, newdata, type = "survival", age_range = ages)  # n x |ages|
              ibs <- .ibs_from_Spred(newdata, S_pred, ages, normalize = normalize_IBS)
              out$IBS <- ibs$IBS
              out$IBS_by_age <- ibs$IBS_by_age
            }

            out
          })

# ============================================================
# MTPModel: predict/evaluate (mob nodes -> Gompertz PAC per node)
# ============================================================

setMethod("predict", "MTPModel",
          function(object, newdata = NULL,
                   type = c("survival","hazard","loglik", "group", "par"),
                   age_range = 80:115) {
            type <- match.arg(type)
            ages <- sort(as.numeric(age_range))
            tnodes <- rownames(object@mob_coef)
            if (is.null(newdata)) {
              newdata <- object@IMM_filled@test_fillna
              newdata$group <- object@mob_tnodes_test
            } else {
              newdata$group <- predict(object@mobfit, newdata, type = "node")
            }
            mob_coef <- object@mob_coef[, 2:1]  # reorder to (a, b)

            if (type %in% c("survival","hazard")) {
              M <- matrix(NA_real_, nrow(newdata), length(ages))
              for (nodei in tnodes) {
                idx <- which(newdata$group == nodei)
                if (!length(idx)) next
                pac <- GompertzPAC()
                pac@params <- mob_coef[match(nodei, tnodes), ]
                if (type == "survival") {
                  S_age <- pac@survival_(pac@params, ages)
                  S_ba  <- pac@survival_(pac@params, newdata$birthage[idx])
                  B     <- matrix(rep(S_age, each = length(idx)), nrow = length(idx))
                  B     <- sweep(B, 1, S_ba, "/")
                  for (k in seq_along(idx)) {
                    younger <- which(ages < newdata$birthage[idx[k]])
                    if (length(younger)) B[k, younger] <- 1
                  }
                  M[idx, ] <- B
                } else {
                  mu_age <- pac@mu_(pac@params, ages)
                  M[idx, ] <- matrix(rep(mu_age, each = length(idx)), nrow = length(idx))
                }
              }
              colnames(M) <- as.character(ages)
              return(M)
            }

            # type == "loglik"
            ll <- rep(NA_real_, nrow(newdata))
            for (nodei in tnodes) {
              idx <- which(newdata$group == nodei)
              if (!length(idx)) next
              pac <- GompertzPAC()
              pac@params <- mob_coef[match(nodei, tnodes), ]
              ll[idx] <- logllh(pac,
                                par = pac@params,
                                x = newdata$birthage[idx],
                                r = newdata$censoredage[idx],
                                i = newdata$DthIndicator[idx])
            }

            if (type == "group") return( newdata$group)
            if (type == "par")   return( mob_coef[match(newdata$group, tnodes), , drop = FALSE])

            names(ll) <- rownames(newdata)
            ll
          })

setMethod("evaluate", "MTPModel",
          function(object, newdata = NULL,
                   metrics = c("AIC","loglik_sum","loglik_vec","IBS"),
                   age_range = 80:115, normalize_IBS = TRUE, ...) {
            if (is.null(newdata)) {
              newdata <- object@IMM_filled@test_fillna
              newdata$group <- object@mob_tnodes_test
            }
            ages <- sort(as.numeric(age_range))
            out <- list()

            # AIC not defined for the piecewise-node model; return NA
            if ("AIC" %in% metrics) out$AIC <- NA_real_

            if ("loglik_vec" %in% metrics || "loglik_sum" %in% metrics) {
              ll_vec <- predict(object, newdata, type = "loglik")
              if ("loglik_vec" %in% metrics) out$loglik_vec <- ll_vec
              if ("loglik_sum" %in% metrics) out$loglik_sum <- sum(ll_vec, na.rm = TRUE)
            }

            if ("IBS" %in% metrics) {
              S_pred <- predict(object, newdata, type = "survival", age_range = ages)
              ibs <- .ibs_from_Spred(newdata, S_pred, ages, normalize = normalize_IBS)
              out$IBS <- ibs$IBS
              out$IBS_by_age <- ibs$IBS_by_age
            }
            out
          })

# ============================================================
# GPHModel: predict/evaluate (per-individual Gompertz PH)
# ============================================================

setMethod("predict", "GPHModel",
          function(object, newdata = NULL,
                   type = c("survival","hazard","loglik", "par"),
                   age_range = 80:115) {
            type <- match.arg(type)
            ages <- sort(as.numeric(age_range))
            if (is.null(newdata)) newdata <- object@IMM_filled@test_fillna

            # shape (b) common; alpha_i varies via gpfit_pred (stored on object)
            b <- as.numeric(object@gpfit_shape)
            # If predicting on newdata different from test_fillna, recompute lp quickly:
            if (!identical(newdata, object@IMM_filled@test_fillna)) {
              # best-effort: use flexsurv predict with type = "lp"
              lp <- predict(object@gpfit, newdata = newdata, type = "lp")$.pred_link
              alpha_vec <- log(lp)
            } else {
              alpha_vec <- object@gpfit_pred
            }

            if (type %in% c("survival","hazard")) {
              M <- matrix(NA_real_, nrow(newdata), length(ages))
              for (i in seq_len(nrow(newdata))) {
                pac <- GompertzPAC()
                pac@params <- c(alpha_vec[i], b)
                if (type == "survival") {
                  S_age <- pac@survival_(pac@params, ages)
                  S_ba  <- pac@survival_(pac@params, newdata$birthage[i])
                  v     <- S_age / S_ba
                  v[ages < newdata$birthage[i]] <- 1
                  M[i, ] <- v
                } else {
                  M[i, ] <- pac@mu_(pac@params, ages)
                }
              }
              colnames(M) <- as.character(ages)
              return(M)
            }

            # type == "loglik" (per-individual)
            ll <- rep(NA_real_, nrow(newdata))
            for (i in seq_len(nrow(newdata))) {
              pac <- GompertzPAC()
              pac@params <- c(alpha_vec[i], b)
              ll[i] <- logllh(pac,
                              par = pac@params,
                              x = newdata$birthage[i],
                              r = newdata$censoredage[i],
                              i = newdata$DthIndicator[i])
            }

            if (type == "par") return( cbind(alpha = alpha_vec, shape = rep(b, nrow(newdata))) )

            names(ll) <- rownames(newdata)
            ll
          })

setMethod("evaluate", "GPHModel",
          function(object, newdata = NULL,
                   metrics = c("AIC","loglik_sum","loglik_vec","IBS"),
                   age_range = 80:115, normalize_IBS = TRUE, ...) {
            if (is.null(newdata)) newdata <- object@IMM_filled@test_fillna
            ages <- sort(as.numeric(age_range))
            out <- list()

            # AIC available via flexsurvreg
            if ("AIC" %in% metrics) out$AIC <- tryCatch(stats::AIC(object@gpfit), error = function(e) NA_real_)

            if ("loglik_vec" %in% metrics || "loglik_sum" %in% metrics) {
              ll_vec <- predict(object, newdata, type = "loglik")
              if ("loglik_vec" %in% metrics) out$loglik_vec <- ll_vec
              if ("loglik_sum" %in% metrics) out$loglik_sum <- sum(ll_vec, na.rm = TRUE)
            }


            if ("IBS" %in% metrics) {
              S_pred <- predict(object, newdata, type = "survival", age_range = ages)
              ibs <- .ibs_from_Spred(newdata, S_pred, ages, normalize = normalize_IBS)
              out$IBS <- ibs$IBS
              out$IBS_by_age <- ibs$IBS_by_age
            }

            out
          })

# ============================================================
# (Optional) STModel: node predictions only
# ============================================================
setMethod("predict", "STModel",
          function(object, newdata = NULL,
                   type = c("survival", "node"),
                   age_range = 80:115) {
            type <- match.arg(type)
            if (is.null(newdata)) newdata <- object@IMM@data_test
            if (type == "survival") {

            }
            if (type == "node")
              return(predict(object@model %>% partykit::as.party(), newdata = newdata, type = "node"))
          })

setMethod("evaluate", "STModel",
          function(object, newdata = NULL, ...) {
            if (is.null(newdata)) newdata <- object@IMM@data_test
            preds <- predict(object, newdata, type = "node")
            list(nodes = object@tnodes,
                 n_by_node = as.integer(table(factor(preds, levels = object@tnodes))))
          })
